
log.info('Registering TJ Items')
content.createItem('eternitycrystal').register()
content.createItem('eternityingot').register()
content.createItem('infinitycrystal').register()
content.createItem('refinedchaoscrystal').register()
content.createItem('refinedchaosshard').register()
content.createItem('steammotor').register()
content.createItem('steampiston').register()
content.createItem('hotiron').register()