import gregtech.api.GTValues
import gregtech.api.recipes.RecipeMaps
import gregtech.api.unification.OreDictUnifier
import gregtech.api.unification.material.Materials
import gregtech.api.unification.ore.OrePrefix
import gregtech.common.metatileentities.MetaTileEntities

// memory card (items) 10 B
crafting.shapedBuilder()
        .row('   ')
        .row('PCP')
        .row('PHP')
        .key('P', item('enderio:item_alloy_ingot', 5))
        .key('C', ore('circuitIv'))
        .key('H', MetaTileEntities.HULL[GTValues.IV].getStackForm())
        .output(item('enderutilities:enderpart', 53))
        .replace()
        .register()
// ender capacitor (advanced)
crafting.shapedBuilder()
        .row(' E ')
        .row('SCS')
        .row('OSO')
        .key('E', OreDictUnifier.get(OrePrefix.gem, Materials.EnderPearl))
        .key('S', item('enderio:item_alloy_ingot', 8))
        .key('C', ore('circuitHv'))
        .key('O', ore('obsidian'))
        .output(item('enderutilities:endercapacitor', 2))
        .replace()
        .register()
// inactive ender core (advanced)
crafting.shapedBuilder()
        .row('OSO')
        .row('SCS')
        .row('OSO')
        .key('O', ore('obsidian'))
        .key('S', item('enderio:item_alloy_ingot', 8))
        .key('C', ore('circuitHv'))
        .output(item('enderutilities:enderpart', 12))
        .replace()
        .register()
// creative breaking module
crafting.shapedBuilder()
        .row('SNS')
        .row(' E ')
        .row(' E ')
        .key('S', item('enderio:item_alloy_ingot', 8))
        .key('N', OreDictUnifier.get(OrePrefix.gem, Materials.NetherStar))
        .key('E', item('enderutilities:enderpart', 20))
        .output(item('enderutilities:enderpart', 30))
        .replace()
        .register()
// wand of the lazy builder
crafting.shapedBuilder()
        .row('C  ')
        .row(' E ')
        .row('  E')
        .key('C', item('enderutilities:enderpart', 17))
        .key('E', item('enderio:item_alloy_ingot', 8))
        .output(item('enderutilities:builderswand'))
        .replace()
        .register()
// advanced ender porter
crafting.shapedBuilder()
        .row('ESE')
        .row('SCS')
        .row('ESE')
        .key('E', OreDictUnifier.get(OrePrefix.gem, Materials.EnderEye))
        .key('S', item('enderio:item_alloy_ingot', 8))
        .key('C', item('enderutilities:enderpart', 17))
        .output(item('enderutilities:enderporter', 1))
        .replace()
        .register()
// ender sword
crafting.shapedBuilder()
        .row(' S ')
        .row(' S ')
        .row(' E ')
        .key('S', item('enderio:item_alloy_ingot', 8))
        .key('E', item('enderutilities:enderpart', 20))
        .output(item('enderutilities:endersword'))
        .replace()
        .register()
// ender pickaxe
crafting.shapedBuilder()
        .row('SSS')
        .row(' E ')
        .row(' E ')
        .key('S', item('enderio:item_alloy_ingot', 8))
        .key('E', item('enderutilities:enderpart', 20))
        .output(item('enderutilities:endertool'))
        .replace()
        .register()
// ender axe
crafting.shapedBuilder()
        .row('SS ')
        .row('SE ')
        .row(' E ')
        .key('S', item('enderio:item_alloy_ingot', 8))
        .key('E', item('enderutilities:enderpart', 20))
        .output(item('enderutilities:endertool', 1))
        .replace()
        .register()
// ender shovel
crafting.shapedBuilder()
        .row(' S ')
        .row(' E ')
        .row(' E ')
        .key('S', item('enderio:item_alloy_ingot', 8))
        .key('E', item('enderutilities:enderpart', 20))
        .output(item('enderutilities:endertool', 2))
        .replace()
        .register()
// ender hoe
crafting.shapedBuilder()
        .row('SS ')
        .row(' E ')
        .row(' E ')
        .key('S', item('enderio:item_alloy_ingot', 8))
        .key('E', item('enderutilities:enderpart', 20))
        .output(item('enderutilities:endertool', 3))
        .replace()
        .register()
// living matter manipulator
crafting.shapedBuilder()
        .row('VVV')
        .row('SCV')
        .row('  V')
        .key('V', item('enderio:item_alloy_ingot', 2))
        .key('S', item('enderio:item_alloy_ingot', 8))
        .key('C', item('enderutilities:enderpart', 11))
        .output(item('enderutilities:livingmanipulator'))
        .replace()
        .register()
// portal scaler
crafting.shapedBuilder()
        .row('OGO')
        .row('OCO')
        .row('OSO')
        .key('O', ore('obsidian'))
        .key('G', ore('blockGlassPurple'))
        .key('C', item('enderutilities:enderpart', 17))
        .key('S', item('enderio:item_alloy_ingot', 8))
        .output(item('enderutilities:portalscaler'))
        .replace()
        .register()
// void pickaxe
crafting.shapedBuilder()
        .row('SSS')
        .row('LEL')
        .row('FEF')
        .key('S', item('enderio:item_alloy_ingot', 8))
        .key('L', item('minecraft:lava_bucket'))
        .key('E', item('enderutilities:enderpart', 20))
        .key('F', item('minecraft:fire_charge'))
        .output(item('enderutilities:void_pickaxe'))
        .replace()
        .register()
// energy bridge receiver
crafting.shapedBuilder()
        .row('SGS')
        .row('GCG')
        .row('SGS')
        .key('S', item('enderio:item_alloy_ingot', 8))
        .key('G', ore('blockGlass'))
        .key('C', item('enderutilities:enderpart', 17))
        .output(item('enderutilities:energy_bridge', 1))
        .replace()
        .register()
// energy bridge transmitter
crafting.shapedBuilder()
        .row('SNS')
        .row('SCS')
        .row('SGS')
        .key('S', item('enderio:item_alloy_ingot', 8))
        .key('N', OreDictUnifier.get(OrePrefix.gem, Materials.NetherStar))
        .key('C', item('enderutilities:enderpart', 17))
        .key('G', ore('blockGlass'))
        .output(item('enderutilities:energy_bridge', 2))
        .replace()
        .register()
// massive storage unit
crafting.shapedBuilder()
        .row('SHS')
        .row('SCS')
        .row('SHS')
        .key('S', item('enderio:item_alloy_ingot', 8))
        .key('H', item('enderutilities:storage_0', 5))
        .key('C', item('enderutilities:enderpart', 17))
        .output(item('enderutilities:msu'))
        .replace()
        .register()
// end steel ingot
RecipeMaps.ALLOY_SMELTER_RECIPES.recipeBuilder()
        .inputs(item('enderio:item_alloy_ingot'))
        .input(OrePrefix.gem, Materials.EnderEye)
        .outputs(item('enderio:item_alloy_ingot', 8))
        .EUt(1024).duration(160)
        .buildAndRegister()