import gregtech.api.GTValues
import gregtech.api.recipes.RecipeMaps
import gregtech.api.unification.OreDictUnifier
import gregtech.api.unification.material.MarkerMaterials
import gregtech.api.unification.material.Materials
import gregtech.api.unification.ore.OrePrefix
import gregtech.common.items.MetaItems
import gregtech.common.metatileentities.MetaTileEntities

// handy bag
crafting.shapedBuilder()
        .row('PBP')
        .row('BCB')
        .row('PBP')
        .key('P', item('enderio:item_alloy_ingot', 5))
        .key('B', item('retro_sophisticated_backpacks:backpack_obsidian'))
        .key('C', ore('circuitHv'))
        .output(item('enderutilities:handybag'))
        .replace()
        .register()
// memory card (items) 6 B
crafting.removeByOutput(item('enderutilities:enderpart', 51))
crafting.shapedBuilder()
        .row('   ')
        .row('PCP')
        .row('PBP')
        .key('P', item('enderio:item_alloy_ingot', 5))
        .key('C', ore('circuitHv'))
        .key('B', MetaTileEntities.HULL[GTValues.HV].getStackForm())
        .output(item('enderutilities:enderpart', 51))
        .register()
// launch pad
crafting.removeByOutput(item('advancedrocketry:launchpad'))
RecipeMaps.MIXER_RECIPES.recipeBuilder()
        .input(OrePrefix.block, Materials.Concrete, 3)
        .input(OrePrefix.dye, MarkerMaterials.Color.Yellow)
        .input(OrePrefix.dye, MarkerMaterials.Color.Black)
        .outputs(item('advancedrocketry:launchpad') * 3)
        .EUt(16).duration(240)
        .buildAndRegister()
// space helmet
crafting.shapedBuilder()
        .row('WPW')
        .row('WLW')
        .row('PSP')
        .key('W', ore('wool'))
        .key('P', OreDictUnifier.get(OrePrefix.plate, Materials.StainlessSteel))
        .key('L', OreDictUnifier.get(OrePrefix.craftingLens, MarkerMaterials.Color.White))
        .key('S', item('minecraft:leather_helmet'))
        .output(item('advancedrocketry:spacehelmet'))
        .replace()
        .register()
// space suit chest-piece
crafting.shapedBuilder()
        .row(' P ')
        .row('WSW')
        .row('PWP')
        .key('P', OreDictUnifier.get(OrePrefix.plate, Materials.StainlessSteel))
        .key('W', ore('wool'))
        .key('S', item('minecraft:leather_chestplate'))
        .output(item('advancedrocketry:spacechestplate'))
        .replace()
        .register()
// space suit leggings
crafting.shapedBuilder()
        .row('PWP')
        .row('WSW')
        .row('W W')
        .key('P', OreDictUnifier.get(OrePrefix.plate, Materials.StainlessSteel))
        .key('W', ore('wool'))
        .key('S', item('minecraft:leather_leggings'))
        .output(item('advancedrocketry:spaceleggings'))
        .replace()
        .register()
// space boots
crafting.shapedBuilder()
        .row('PWP')
        .row('WSW')
        .row('PWP')
        .key('P', OreDictUnifier.get(OrePrefix.plate, Materials.StainlessSteel))
        .key('W', ore('wool'))
        .key('S', item('minecraft:leather_boots'))
        .output(item('advancedrocketry:spaceboots'))
        .replace()
        .register()
// holo-projector
crafting.shapedBuilder()
        .row('GEG')
        .row(' H ')
        .row('   ')
        .key('G', ore('paneGlass'))
        .key('E', MetaItems.EMITTER_HV.getStackForm())
        .key('H', MetaTileEntities.HULL[GTValues.HV].getStackForm())
        .output(item('libvulpes:holoprojector'))
        .replace()
        .register()
// gas charge pad
crafting.shapedBuilder()
        .row('   ')
        .row('SPS')
        .row(' D ')
        .key('S', OreDictUnifier.get(OrePrefix.plate, Materials.StainlessSteel))
        .key('P', MetaItems.ELECTRIC_PUMP_HV.getStackForm())
        .key('D', MetaTileEntities.BRONZE_DRUM.getStackForm())
        .output(item('advancedrocketry:oxygencharger'))
        .replace()
        .register()
// fueling station
crafting.shapedBuilder()
        .row('SPS')
        .row('PHP')
        .row('SPS')
        .key('S', OreDictUnifier.get(OrePrefix.plate, Materials.StainlessSteel))
        .key('P', MetaItems.ELECTRIC_PUMP_HV.getStackForm())
        .key('H', MetaTileEntities.HULL[GTValues.HV].getStackForm())
        .output(item('advancedrocketry:fuelingstation'))
        .replace()
        .register()
// rocket assembling machine
crafting.shapedBuilder()
        .row('TUT')
        .row('RHR')
        .row('T T')
        .key('T', OreDictUnifier.get(OrePrefix.plate, Materials.Titanium))
        .key('U', item('advancedrocketry:misc'))
        .key('R', MetaItems.ROBOT_ARM_HV.getStackForm())
        .key('H', MetaTileEntities.HULL[GTValues.HV].getStackForm())
        .output(item('advancedrocketry:rocketbuilder'))
        .replace()
        .register()
// guidance computer
crafting.shapedBuilder()
        .row('IUI')
        .row('EHE')
        .row('ISI')
        .key('I', OreDictUnifier.get(OrePrefix.plate, Materials.Iron))
        .key('U', item('advancedrocketry:misc'))
        .key('E', MetaItems.EMITTER_HV.getStackForm())
        .key('H', MetaTileEntities.HULL[GTValues.HV].getStackForm())
        .key('S', MetaItems.SENSOR_HV.getStackForm())
        .output(item('advancedrocketry:guidancecomputer'))
        .replace()
        .register()
// liquid fueled engine
crafting.shapedBuilder()
        .row(' S ')
        .row('S S')
        .row('PPP')
        .key('S', OreDictUnifier.get(OrePrefix.stick, Materials.Steel))
        .key('P', OreDictUnifier.get(OrePrefix.plate, Materials.StainlessSteel))
        .output(item('advancedrocketry:rocketmotor'))
        .replace()
        .register()
// liquid fuel tank
crafting.shapedBuilder()
        .row('SPS')
        .row('P P')
        .row('SPS')
        .key('S', OreDictUnifier.get(OrePrefix.stick, Materials.StainlessSteel))
        .key('P', OreDictUnifier.get(OrePrefix.plate, Materials.StainlessSteel))
        .output(item('advancedrocketry:fueltank') * 2)
        .replace()
        .register()
// satellite id chip
crafting.shapedBuilder()
        .row('   ')
        .row(' A ')
        .row('BBB')
        .key('A', item('advancedrocketry:ic', 2))
        .key('B', item('advancedrocketry:ic'))
        .output(item('advancedrocketry:satelliteidchip'))
        .replace()
        .register()
// silicon wafer
RecipeMaps.ALLOY_SMELTER_RECIPES.recipeBuilder()
        .inputs(item('minecraft:glass_pane'))
        .input(MetaItems.SILICON_WAFER)
        .outputs(item('advancedrocketry:wafer'))
        .EUt(30).duration(160)
        .buildAndRegister()
// basic circuit plate
RecipeMaps.LASER_ENGRAVER_RECIPES.recipeBuilder()
        .notConsumable(OrePrefix.craftingLens, MarkerMaterials.Color.White)
        .inputs(item('advancedrocketry:wafer'))
        .outputs(item('advancedrocketry:itemcircuitplate'))
        .EUt(30).duration(160)
        .buildAndRegister()
// advanced circuit plate
RecipeMaps.LASER_ENGRAVER_RECIPES.recipeBuilder()
        .notConsumable(OrePrefix.craftingLens, MarkerMaterials.Color.Lime)
        .inputs(item('advancedrocketry:wafer'))
        .outputs(item('advancedrocketry:itemcircuitplate', 1))
        .EUt(30).duration(160)
        .buildAndRegister()
// basic circuit
RecipeMaps.CUTTER_RECIPES.recipeBuilder()
        .inputs(item('advancedrocketry:itemcircuitplate'))
        .fluidInputs(Materials.Lubricant.getFluid(144))
        .outputs(item('advancedrocketry:ic') * 16)
        .EUt(30).duration(160)
        .buildAndRegister()
// advanced circuit
RecipeMaps.CUTTER_RECIPES.recipeBuilder()
        .inputs(item('advancedrocketry:itemcircuitplate', 1))
        .fluidInputs(Materials.Lubricant.getFluid(144))
        .outputs(item('advancedrocketry:ic', 2) * 16)
        .EUt(30).duration(160)
        .buildAndRegister()
// ender capacitor (advanced)
crafting.shapedBuilder()
        .row(' E ')
        .row('SCS')
        .row('OSO')
        .key('E', OreDictUnifier.get(OrePrefix.gem, Materials.EnderPearl))
        .key('S', item('enderio:item_alloy_ingot', 8))
        .key('C', ore('circuitHv'))
        .key('O', ore('obsidian'))
        .output(item('enderutilities:endercapacitor', 2))
        .replace()
        .register()
// inactive ender core (advanced)
crafting.shapedBuilder()
        .row('OSO')
        .row('SCS')
        .row('OSO')
        .key('O', ore('obsidian'))
        .key('S', item('enderio:item_alloy_ingot', 8))
        .key('C', ore('circuitHv'))
        .output(item('enderutilities:enderpart', 12))
        .replace()
        .register()
// creative breaking module
crafting.shapedBuilder()
        .row('SNS')
        .row(' E ')
        .row(' E ')
        .key('S', item('enderio:item_alloy_ingot', 8))
        .key('N', OreDictUnifier.get(OrePrefix.gem, Materials.NetherStar))
        .key('E', item('enderutilities:enderpart', 20))
        .output(item('enderutilities:enderpart', 30))
        .replace()
        .register()
// wand of the lazy builder
crafting.shapedBuilder()
        .row('C  ')
        .row(' E ')
        .row('  E')
        .key('C', item('enderutilities:enderpart', 17))
        .key('E', item('enderio:item_alloy_ingot', 8))
        .output(item('enderutilities:builderswand'))
        .replace()
        .register()
// advanced ender porter
crafting.shapedBuilder()
        .row('ESE')
        .row('SCS')
        .row('ESE')
        .key('E', OreDictUnifier.get(OrePrefix.gem, Materials.EnderEye))
        .key('S', item('enderio:item_alloy_ingot', 8))
        .key('C', item('enderutilities:enderpart', 17))
        .output(item('enderutilities:enderporter', 1))
        .replace()
        .register()
// ender sword
crafting.shapedBuilder()
        .row(' S ')
        .row(' S ')
        .row(' E ')
        .key('S', item('enderio:item_alloy_ingot', 8))
        .key('E', item('enderutilities:enderpart', 20))
        .output(item('enderutilities:endersword'))
        .replace()
        .register()
// ender pickaxe
crafting.shapedBuilder()
        .row('SSS')
        .row(' E ')
        .row(' E ')
        .key('S', item('enderio:item_alloy_ingot', 8))
        .key('E', item('enderutilities:enderpart', 20))
        .output(item('enderutilities:endertool'))
        .replace()
        .register()
// ender axe
crafting.shapedBuilder()
        .row('SS ')
        .row('SE ')
        .row(' E ')
        .key('S', item('enderio:item_alloy_ingot', 8))
        .key('E', item('enderutilities:enderpart', 20))
        .output(item('enderutilities:endertool', 1))
        .replace()
        .register()
// ender shovel
crafting.shapedBuilder()
        .row(' S ')
        .row(' E ')
        .row(' E ')
        .key('S', item('enderio:item_alloy_ingot', 8))
        .key('E', item('enderutilities:enderpart', 20))
        .output(item('enderutilities:endertool', 2))
        .replace()
        .register()
// ender hoe
crafting.shapedBuilder()
        .row('SS ')
        .row(' E ')
        .row(' E ')
        .key('S', item('enderio:item_alloy_ingot', 8))
        .key('E', item('enderutilities:enderpart', 20))
        .output(item('enderutilities:endertool', 3))
        .replace()
        .register()
// living matter manipulator
crafting.shapedBuilder()
        .row('VVV')
        .row('SCV')
        .row('  V')
        .key('V', item('enderio:item_alloy_ingot', 2))
        .key('S', item('enderio:item_alloy_ingot', 8))
        .key('C', item('enderutilities:enderpart', 11))
        .output(item('enderutilities:livingmanipulator'))
        .replace()
        .register()
// portal scaler
crafting.shapedBuilder()
        .row('OGO')
        .row('OCO')
        .row('OSO')
        .key('O', ore('obsidian'))
        .key('G', ore('blockGlassPurple'))
        .key('C', item('enderutilities:enderpart', 17))
        .key('S', item('enderio:item_alloy_ingot', 8))
        .output(item('enderutilities:portalscaler'))
        .replace()
        .register()
// void pickaxe
crafting.shapedBuilder()
        .row('SSS')
        .row('LEL')
        .row('FEF')
        .key('S', item('enderio:item_alloy_ingot', 8))
        .key('L', item('minecraft:lava_bucket'))
        .key('E', item('enderutilities:enderpart', 20))
        .key('F', item('minecraft:fire_charge'))
        .output(item('enderutilities:void_pickaxe'))
        .replace()
        .register()
// energy bridge receiver
crafting.shapedBuilder()
        .row('SGS')
        .row('GCG')
        .row('SGS')
        .key('S', item('enderio:item_alloy_ingot', 8))
        .key('G', ore('blockGlass'))
        .key('C', item('enderutilities:enderpart', 17))
        .output(item('enderutilities:energy_bridge', 1))
        .replace()
        .register()
// energy bridge transmitter
crafting.shapedBuilder()
        .row('SNS')
        .row('SCS')
        .row('SGS')
        .key('S', item('enderio:item_alloy_ingot', 8))
        .key('N', OreDictUnifier.get(OrePrefix.gem, Materials.NetherStar))
        .key('C', item('enderutilities:enderpart', 17))
        .key('G', ore('blockGlass'))
        .output(item('enderutilities:energy_bridge', 2))
        .replace()
        .register()
// massive storage unit
crafting.shapedBuilder()
        .row('SHS')
        .row('SCS')
        .row('SHS')
        .key('S', item('enderio:item_alloy_ingot', 8))
        .key('H', item('enderutilities:storage_0', 5))
        .key('C', item('enderutilities:enderpart', 17))
        .output(item('enderutilities:msu'))
        .replace()
        .register()
// large memory chest
crafting.shapedBuilder()
        .row(' C ')
        .row(' H ')
        .row(' H ')
        .key('C', ore('circuitIv'))
        .key('H', item('enderutilities:storage_0', 1))
        .output(item('enderutilities:storage_0', 2))
        .replace()
        .register()
// handy chest (large)
crafting.shapedBuilder()
        .row(' C ')
        .row(' H ')
        .row(' C ')
        .key('C', ore('circuitIv'))
        .key('H', item('enderutilities:storage_0', 4))
        .output(item('enderutilities:storage_0', 5))
        .replace()
        .register()
// centrifuge
mods.advancedrocketry.centrifuge.removeAll()
// chemical reactor
mods.advancedrocketry.chemical_reactor.removeAll()
// crystallizer
mods.advancedrocketry.crystallizer.removeAll()
// cutting machine
mods.advancedrocketry.cutting_machine.removeAll()
// electirc arc furnace
mods.advancedrocketry.electric_arc_furnace.removeAll()
// electrolyzer
mods.advancedrocketry.electrolyser.removeAll()
// lathe
mods.advancedrocketry.lathe.removeAll()
// precision assembler
mods.advancedrocketry.precision_assembler.removeAll()
// rolling machine
mods.advancedrocketry.rolling_machine.removeAll()
