import gregtech.api.GTValues
import gregtech.api.recipes.RecipeMaps
import gregtech.api.unification.OreDictUnifier
import gregtech.api.unification.material.MarkerMaterials
import gregtech.api.unification.material.Materials
import gregtech.api.unification.ore.OrePrefix
import gregtech.common.metatileentities.MetaTileEntities

// farming station
crafting.removeByOutput(item('enderio:block_farm_station'))
RecipeMaps.ASSEMBLER_RECIPES.recipeBuilder()
        .circuitMeta(0)
        .inputs(item('enderio:item_material', 41), item('minecraft:diamond_hoe'))
        .input(OrePrefix.circuit, MarkerMaterials.Tier.LV, 2)
        .input(MetaTileEntities.HULL[GTValues.LV])
        .outputs(item('enderio:block_farm_station'))
        .EUt(30).duration(160)
        .buildAndRegister()

// tool casing
crafting.addShapeless(item('thermalfoundation:material', 640), [item('actuallyadditions:item_misc', 16)])
// item dislocator
crafting.removeByOutput(item('draconicevolution:magnet'))
RecipeMaps.ASSEMBLER_RECIPES.recipeBuilder()
        .input(OrePrefix.circuit, MarkerMaterials.Tier.LV, 2)
        .input(OrePrefix.dust, Materials.Redstone, 2)
        .inputs(item('enderio:item_alloy_ingot') * 4)
        .outputs(item('draconicevolution:magnet'))
        .EUt(28).duration(100)
        .buildAndRegister()
// Z-logic controller
crafting.shapedBuilder()
        .row('SIS')
        .row('DZD')
        .row('DRD')
        .key('S', item('enderio:item_alloy_ingot', 7))
        .key('I', OreDictUnifier.get(OrePrefix.ingot, Materials.Iron))
        .key('D', OreDictUnifier.get(OrePrefix.dust, Materials.Silicon))
        .key('Z', item('minecraft:skull', 2))
        .key('R', OreDictUnifier.get(OrePrefix.block, Materials.Redstone))
        .output(item('enderio:item_material', 41))
        .register()
// ender capacitor (enhanced)
crafting.shapedBuilder()
        .row(' E ')
        .row('VCV')
        .row('OVO')
        .key('E', OreDictUnifier.get(OrePrefix.gem, Materials.EnderPearl))
        .key('V', item('enderio:item_alloy_ingot', 2))
        .key('C', ore('circuitMv'))
        .key('O', ore('obsidian'))
        .output(item('enderutilities:endercapacitor', 1))
        .replace()
        .register()
// inactive ender core (enhanced)
crafting.shapedBuilder()
        .row('OVO')
        .row('VCV')
        .row('OVO')
        .key('O', ore('obsidian'))
        .key('V', item('enderio:item_alloy_ingot', 2))
        .key('C', ore('circuitMv'))
        .output(item('enderutilities:enderpart', 11))
        .replace()
        .register()
// ender bow
crafting.shapedBuilder()
        .row('RV ')
        .row('RCV')
        .row('RV ')
        .key('R', item('enderutilities:enderpart', 21))
        .key('V', item('enderio:item_alloy_ingot', 2))
        .key('C', item('enderutilities:enderpart', 11))
        .output(item('enderutilities:enderbow'))
        .replace()
        .register()
// ender lasso
crafting.shapedBuilder()
        .row('RR ')
        .row('RC ')
        .row('  P')
        .key('R', item('enderutilities:enderpart', 21))
        .key('C', item('enderutilities:enderpart', 11))
        .key('P', item('enderio:item_alloy_ingot', 5))
        .output(item('enderutilities:enderlasso'))
        .replace()
        .register()
// elite ender pearl
crafting.shapedBuilder()
        .row('FVF')
        .row('VPV')
        .row('FCF')
        .key('F', ore('feather'))
        .key('V', item('enderio:item_alloy_ingot', 2))
        .key('P', item('enderutilities:enderpearlreusable'))
        .key('C', item('enderutilities:enderpart', 10))
        .output(item('enderutilities:enderpearlreusable', 1))
        .replace()
        .register()
// ender porter
crafting.shapedBuilder()
        .row('EVE')
        .row('VCV')
        .row('EVE')
        .key('E', OreDictUnifier.get(OrePrefix.gem, Materials.EnderEye))
        .key('V', item('enderio:item_alloy_ingot', 2))
        .key('C', item('enderutilities:enderpart', 16))
        .output(item('enderutilities:enderporter'))
        .replace()
        .register()
// nullifier - 1 / 9
crafting.shapedBuilder()
        .row('CLC')
        .row('PDP')
        .row('CLC')
        .key('C', ore('chestWood'))
        .key('L', item('minecraft:lava_bucket'))
        .key('P', item('enderio:item_alloy_ingot', 5))
        .key('D', item('danknull:dank_null_1'))
        .output(item('enderutilities:nullifier'))
        .replace()
        .register()
// item pickup manager - pre: 1 LC: 0
crafting.shapedBuilder()
        .row('VHV')
        .row('VEV')
        .row('VRV')
        .key('V', item('enderio:item_alloy_ingot', 2))
        .key('H', item('minecraft:hopper'))
        .key('E', item('minecraft:ender_chest'))
        .key('R', item('minecraft:comparator'))
        .output(item('enderutilities:pickupmanager'))
        .replace()
        .register()
// syringe (empty)
crafting.shapedBuilder()
        .row('V  ')
        .row(' G ')
        .row('  E')
        .key('V', item('enderio:item_alloy_ingot', 2))
        .key('G', ore('blockGlass'))
        .key('E', item('enderutilities:enderpart', 20))
        .output(item('enderutilities:syringe'))
        .replace()
        .register()
// energy bridge resonator
crafting.shapedBuilder()
        .row('VGV')
        .row('GCG')
        .row('VVV')
        .key('V', item('enderio:item_alloy_ingot', 2))
        .key('G', ore('blockGlass'))
        .key('C', item('enderutilities:enderpart', 16))
        .output(item('enderutilities:energy_bridge'))
        .replace()
        .register()
// crafting station
crafting.shapedBuilder()
        .row('FTF')
        .row('VCV')
        .row('OVO')
        .key('F', item('enderutilities:machine_0'))
        .key('T', item('minecraft:crafting_table'))
        .key('V', item('enderio:item_alloy_ingot', 2))
        .key('C', item('enderutilities:enderpart', 11))
        .key('O', ore('obsidian'))
        .output(item('enderutilities:machine_1', 2))
        .replace()
        .register()
// molecular exciter
crafting.shapedBuilder()
        .row('VVV')
        .row('GCR')
        .row('VVV')
        .key('V', item('enderio:item_alloy_ingot', 2))
        .key('G', ore('blockGlass'))
        .key('C', item('enderutilities:enderpart', 11))
        .key('R', OreDictUnifier.get(OrePrefix.dust, Materials.Redstone))
        .output(item('enderutilities:molecular_exciter'))
        .replace()
        .register()
