import gregtech.api.GTValues
import gregtech.api.recipes.RecipeMaps
import gregtech.api.unification.OreDictUnifier
import gregtech.api.unification.material.MarkerMaterials
import gregtech.api.unification.material.Materials
import gregtech.api.unification.ore.OrePrefix
import gregtech.common.metatileentities.MetaTileEntities

// farming station
crafting.removeByOutput(item('enderio:block_farm_station'))
RecipeMaps.ASSEMBLER_RECIPES.recipeBuilder()
        .circuitMeta(0)
        .inputs(item('enderio:item_material', 41), item('minecraft:diamond_hoe'))
        .input(OrePrefix.circuit, MarkerMaterials.Tier.LV, 2)
        .input(MetaTileEntities.HULL[GTValues.LV])
        .outputs(item('enderio:block_farm_station'))
        .EUt(30).duration(160)
        .buildAndRegister()

// tool casing
crafting.addShapeless(item('thermalfoundation:material', 640), [item('actuallyadditions:item_misc', 16)])
// item dislocator
crafting.removeByOutput(item('draconicevolution:magnet'))
RecipeMaps.ASSEMBLER_RECIPES.recipeBuilder()
        .input(OrePrefix.circuit, MarkerMaterials.Tier.LV, 2)
        .input(OrePrefix.dust, Materials.Redstone, 2)
        .inputs(item('enderio:item_alloy_ingot') * 4)
        .outputs(item('draconicevolution:magnet'))
        .EUt(28).duration(100)
        .buildAndRegister()
// Z-logic controller
crafting.shapedBuilder()
        .row('SIS')
        .row('DZD')
        .row('DRD')
        .key('S', item('enderio:item_alloy_ingot', 7))
        .key('I', OreDictUnifier.get(OrePrefix.ingot, Materials.Iron))
        .key('D', OreDictUnifier.get(OrePrefix.dust, Materials.Silicon))
        .key('Z', item('minecraft:skull', 2))
        .key('R', OreDictUnifier.get(OrePrefix.block, Materials.Redstone))
        .output(item('enderio:item_material', 41))
        .register()
// ender capacitor (enhanced)
crafting.shapedBuilder()
        .row(' E ')
        .row('VCV')
        .row('OVO')
        .key('E', OreDictUnifier.get(OrePrefix.gem, Materials.EnderPearl))
        .key('V', item('enderio:item_alloy_ingot', 2))
        .key('C', ore('circuitMv'))
        .key('O', ore('obsidian'))
        .output(item('enderutilities:endercapacitor', 1))
        .replace()
        .register()
// inactive ender core (enhanced)
crafting.shapedBuilder()
        .row('OVO')
        .row('VCV')
        .row('OVO')
        .key('O', ore('obsidian'))
        .key('V', item('enderio:item_alloy_ingot', 2))
        .key('C', ore('circuitMv'))
        .output(item('enderutilities:enderpart', 11))
        .replace()
        .register()
// ender bow
crafting.shapedBuilder()
        .row('RV ')
        .row('RCV')
        .row('RV ')
        .key('R', item('enderutilities:enderpart', 21))
        .key('V', item('enderio:item_alloy_ingot', 2))
        .key('C', item('enderutilities:enderpart', 11))
        .output(item('enderutilities:enderbow'))
        .replace()
        .register()
// ender lasso
crafting.shapedBuilder()
        .row('RR ')
        .row('RC ')
        .row('  P')
        .key('R', item('enderutilities:enderpart', 21))
        .key('C', item('enderutilities:enderpart', 11))
        .key('P', item('enderio:item_alloy_ingot', 5))
        .output(item('enderutilities:enderlasso'))
        .replace()
        .register()
// elite ender pearl
crafting.shapedBuilder()
        .row('FVF')
        .row('VPV')
        .row('FCF')
        .key('F', ore('feather'))
        .key('V', item('enderio:item_alloy_ingot', 2))
        .key('P', item('enderutilities:enderpearlreusable'))
        .key('C', item('enderutilities:enderpart', 10))
        .output(item('enderutilities:enderpearlreusable', 1))
        .replace()
        .register()
// ender porter
crafting.shapedBuilder()
        .row('EVE')
        .row('VCV')
        .row('EVE')
        .key('E', OreDictUnifier.get(OrePrefix.gem, Materials.EnderEye))
        .key('V', item('enderio:item_alloy_ingot', 2))
        .key('C', item('enderutilities:enderpart', 16))
        .output(item('enderutilities:enderporter'))
        .replace()
        .register()
// nullifier - 1 / 9
crafting.shapedBuilder()
        .row('CLC')
        .row('PDP')
        .row('CLC')
        .key('C', ore('chestWood'))
        .key('L', item('minecraft:lava_bucket'))
        .key('P', item('enderio:item_alloy_ingot', 5))
        .key('D', item('danknull:dank_null_1'))
        .output(item('enderutilities:nullifier'))
        .replace()
        .register()
// item pickup manager - pre: 1 LC: 0
crafting.shapedBuilder()
        .row('VHV')
        .row('VEV')
        .row('VRV')
        .key('V', item('enderio:item_alloy_ingot', 2))
        .key('H', item('minecraft:hopper'))
        .key('E', item('minecraft:ender_chest'))
        .key('R', item('minecraft:comparator'))
        .output(item('enderutilities:pickupmanager'))
        .replace()
        .register()
// syringe (empty)
crafting.shapedBuilder()
        .row('V  ')
        .row(' G ')
        .row('  E')
        .key('V', item('enderio:item_alloy_ingot', 2))
        .key('G', ore('blockGlass'))
        .key('E', item('enderutilities:enderpart', 20))
        .output(item('enderutilities:syringe'))
        .replace()
        .register()
// energy bridge resonator
crafting.shapedBuilder()
        .row('VGV')
        .row('GCG')
        .row('VVV')
        .key('V', item('enderio:item_alloy_ingot', 2))
        .key('G', ore('blockGlass'))
        .key('C', item('enderutilities:enderpart', 16))
        .output(item('enderutilities:energy_bridge'))
        .replace()
        .register()
// crafting station
crafting.shapedBuilder()
        .row('FTF')
        .row('VCV')
        .row('OVO')
        .key('F', item('enderutilities:machine_0'))
        .key('T', item('minecraft:crafting_table'))
        .key('V', item('enderio:item_alloy_ingot', 2))
        .key('C', item('enderutilities:enderpart', 11))
        .key('O', ore('obsidian'))
        .output(item('enderutilities:machine_1', 2))
        .replace()
        .register()
// molecular exciter
crafting.shapedBuilder()
        .row('VVV')
        .row('GCR')
        .row('VVV')
        .key('V', item('enderio:item_alloy_ingot', 2))
        .key('G', ore('blockGlass'))
        .key('C', item('enderutilities:enderpart', 11))
        .key('R', OreDictUnifier.get(OrePrefix.dust, Materials.Redstone))
        .output(item('enderutilities:molecular_exciter'))
        .replace()
        .register()
// electrical steel ingot
RecipeMaps.ALLOY_SMELTER_RECIPES.recipeBuilder()
        .input(OrePrefix.ingot, Materials.Iron)
        .input(OrePrefix.dust, Materials.Silicon)
        .outputs(item('enderio:item_alloy_ingot'))
        .EUt(30).duration(160)
        .buildAndRegister()
// energetic alloy ingot
RecipeMaps.ALLOY_SMELTER_RECIPES.recipeBuilder()
        .input(OrePrefix.ingot, Materials.Gold, 2)
        .input(OrePrefix.dust, Materials.Glowstone)
        .outputs(item('enderio:item_alloy_ingot', 1) * 2)
        .EUt(30).duration(160)
        .buildAndRegister()
// vibrant alloy ingot
RecipeMaps.ALLOY_SMELTER_RECIPES.recipeBuilder()
        .inputs(item('enderio:item_alloy_ingot', 1) * 2)
        .input(OrePrefix.gem, Materials.EnderPearl)
        .outputs(item('enderio:item_alloy_ingot', 2) * 2)
        .EUt(30).duration(160)
        .buildAndRegister()
// redstone alloy ingot
RecipeMaps.ALLOY_SMELTER_RECIPES.recipeBuilder()
        .input(OrePrefix.dust, Materials.Redstone)
        .input(OrePrefix.dust, Materials.Silicon)
        .outputs(item('enderio:item_alloy_ingot', 3))
        .EUt(30).duration(160)
        .buildAndRegister()
// conductive iron ingot
RecipeMaps.ALLOY_SMELTER_RECIPES.recipeBuilder()
        .input(OrePrefix.dust, Materials.Redstone)
        .input(OrePrefix.ingot, Materials.Iron)
        .outputs(item('enderio:item_alloy_ingot', 4))
        .EUt(30).duration(160)
        .buildAndRegister()
// pulsating iron ingot
RecipeMaps.ALLOY_SMELTER_RECIPES.recipeBuilder()
        .input(OrePrefix.ingot, Materials.Iron)
        .input(OrePrefix.dust, Materials.Uranium)
        .outputs(item('enderio:item_alloy_ingot', 5))
        .EUt(30).duration(160)
        .buildAndRegister()
RecipeMaps.ALLOY_SMELTER_RECIPES.recipeBuilder()
        .input(OrePrefix.ingot, Materials.Iron)
        .input(OrePrefix.ingot, Materials.Uranium)
        .outputs(item('enderio:item_alloy_ingot', 5))
        .EUt(30).duration(160)
        .buildAndRegister()
// dark steel ingot
RecipeMaps.ALLOY_SMELTER_RECIPES.recipeBuilder()
        .input(OrePrefix.ingot, Materials.Steel)
        .input(OrePrefix.block, Materials.Obsidian)
        .outputs(item('enderio:item_alloy_ingot', 6))
        .EUt(30).duration(160)
        .buildAndRegister()
// soularium ingot
RecipeMaps.ALLOY_SMELTER_RECIPES.recipeBuilder()
        .inputs(item('minecraft:soul_sand'))
        .input(OrePrefix.ingot, Materials.Gold)
        .outputs(item('enderio:item_alloy_ingot', 7))
        .EUt(30).duration(160)
        .buildAndRegister()
// grains of infinity
RecipeMaps.ARC_FURNACE_RECIPES.recipeBuilder()
        .input(OrePrefix.dust, Materials.Coke, 64)
        .fluidInputs(fluid('fire_water') * 100)
        .outputs(item('enderio:item_material', 20) * 64)
        .EUt(28).duration(120)
        .buildAndRegister()
// conduit binder composite
RecipeMaps.MIXER_RECIPES.recipeBuilder()
        .inputs(item('minecraft:gravel') * 4)
        .input('sand', 4)
        .outputs(item('enderio:item_material', 22) * 16)
        .EUt(500).duration(80)
        .buildAndRegister()
// grains of prescience
RecipeMaps.MACERATOR_RECIPES.recipeBuilder()
        .inputs(item('enderio:item_material', 19))
        .outputs(item('enderio:item_material', 34))
        .EUt(30).duration(160)
        .buildAndRegister()
// grains of piezallity
RecipeMaps.MACERATOR_RECIPES.recipeBuilder()
        .inputs(item('enderio:item_material', 14))
        .outputs(item('enderio:item_material', 36))
        .EUt(30).duration(160)
        .buildAndRegister()
// grains of the end
RecipeMaps.MACERATOR_RECIPES.recipeBuilder()
        .inputs(item('enderio:item_material', 16))
        .outputs(item('enderio:item_material', 37))
        .EUt(30).duration(160)
        .buildAndRegister()
// organic green dye
crafting.shapedBuilder()
        .row(' G ')
        .row('G G')
        .row(' G ')
        .key('G', item('minecraft:tallgrass', 1))
        .output(item('enderio:item_material', 48))
        .register()
// organic brown dye
RecipeMaps.ALLOY_SMELTER_RECIPES.recipeBuilder()
        .input("treeSapling", 4)
        .input(OrePrefix.gem, Materials.Charcoal)
        .outputs(item('enderio:item_material', 49) * 2)
        .EUt(30).duration(160)
        .buildAndRegister()
// organic black dye
RecipeMaps.ALLOY_SMELTER_RECIPES.recipeBuilder()
        .inputs(item('minecraft:tallgrass', 1) * 2)
        .input(OrePrefix.gem, Materials.Coal)
        .outputs(item('enderio:item_material', 50) * 2)
        .EUt(30).duration(160)
        .buildAndRegister()
// soul powder
RecipeMaps.MACERATOR_RECIPES.recipeBuilder()
        .inputs(item('enderio:item_alloy_ingot', 7))
        .outputs(item('enderio:item_material', 74))
        .EUt(30).duration(160)
        .buildAndRegister()
// advanced item filter
crafting.shapedBuilder()
        .row('RDR')
        .row('DID')
        .row('RDR')
        .key('R', OreDictUnifier.get(OrePrefix.plate, Materials.Redstone))
        .key('D', OreDictUnifier.get(OrePrefix.plate, Materials.Diamond))
        .key('I', item('enderio:item_basic_item_filter'))
        .output(item('enderio:item_advanced_item_filter'))
        .replace()
        .register()
// big item filter
crafting.shapedBuilder()
        .row('ARA')
        .row('RIR')
        .row('ARA')
        .key('A', OreDictUnifier.get(OrePrefix.plate, Materials.Aluminium))
        .key('R', OreDictUnifier.get(OrePrefix.plate, Materials.Redstone))
        .key('I', item('enderio:item_basic_item_filter'))
        .output(item('enderio:item_big_item_filter'))
        .replace()
        .register()
// blank dark steel upgrade
RecipeMaps.ASSEMBLER_RECIPES.recipeBuilder()
        .inputs(item('enderio:item_alloy_ingot', 6))
        .input(OrePrefix.plateDouble, Materials.Steel)
        .outputs(item('enderio:item_dark_steel_upgrade'))
        .EUt(30).duration(100)
        .buildAndRegister()
// liquid xp
RecipeMaps.EXTRACTOR_RECIPES.recipeBuilder()
        .inputs(item('actuallyadditions:item_solidified_experience') * 64)
        .fluidOutputs(fluid('xpjuice') * 10000)
        .EUt(30).duration(100)
        .buildAndRegister()
// atomic reconstructor
crafting.removeByOutput(item('actuallyadditions:block_atomic_reconstructor'))
mods.actuallyadditions.atomic_reconstructor.removeAll()
// crusher
crafting.removeByOutput(item('actuallyadditions:block_grinder'))
mods.actuallyadditions.crusher.removeAll()
// double crusher
crafting.removeByOutput(item('actuallyadditions:block_grinder_double'))
// restonia crystal block
RecipeMaps.LASER_ENGRAVER_RECIPES.recipeBuilder()
        .notConsumable(OrePrefix.craftingLens, MarkerMaterials.Color.White)
        .input(OrePrefix.block, Materials.Redstone)
        .outputs(item('actuallyadditions:block_crystal'))
        .EUt(8).duration(20)
        .buildAndRegister()
// palis crystal block
RecipeMaps.LASER_ENGRAVER_RECIPES.recipeBuilder()
        .notConsumable(OrePrefix.craftingLens, MarkerMaterials.Color.White)
        .input(OrePrefix.block, Materials.Lapis)
        .outputs(item('actuallyadditions:block_crystal', 1))
        .EUt(8).duration(20)
        .buildAndRegister()
// diamatine crystal block
RecipeMaps.LASER_ENGRAVER_RECIPES.recipeBuilder()
        .notConsumable(OrePrefix.craftingLens, MarkerMaterials.Color.White)
        .input(OrePrefix.block, Materials.Diamond)
        .outputs(item('actuallyadditions:block_crystal', 2))
        .EUt(8).duration(20)
        .buildAndRegister()
// void crystal block
RecipeMaps.LASER_ENGRAVER_RECIPES.recipeBuilder()
        .notConsumable(OrePrefix.craftingLens, MarkerMaterials.Color.White)
        .input(OrePrefix.block, Materials.Coal)
        .outputs(item('actuallyadditions:block_crystal', 3))
        .EUt(8).duration(20)
        .buildAndRegister()
// emeradic crystal block
RecipeMaps.LASER_ENGRAVER_RECIPES.recipeBuilder()
        .notConsumable(OrePrefix.craftingLens, MarkerMaterials.Color.White)
        .input(OrePrefix.block, Materials.Emerald)
        .outputs(item('actuallyadditions:block_crystal', 4))
        .EUt(8).duration(20)
        .buildAndRegister()
// enori crystal block
RecipeMaps.LASER_ENGRAVER_RECIPES.recipeBuilder()
        .notConsumable(OrePrefix.craftingLens, MarkerMaterials.Color.White)
        .input(OrePrefix.block, Materials.Iron)
        .outputs(item('actuallyadditions:block_crystal', 5))
        .EUt(8).duration(20)
        .buildAndRegister()