import gregtech.api.GTValues
import gregtech.common.items.MetaItems
import gregtech.common.metatileentities.MetaTileEntities

// dolly
crafting.shapedBuilder()
        .row(' PV')
        .row('P V')
        .row('VVS')
        .key('P', MetaItems.ELECTRIC_PISTON_MV.getStackForm())
        .key('V', item('enderio:item_alloy_ingot', 2))
        .key('S', ore('blockSlime'))
        .output(item('enderutilities:dolly'))
        .replace()
        .register()
// small memory chest
crafting.shapedBuilder()
        .row(' C ')
        .row(' H ')
        .row('   ')
        .key('C', ore('circuitHv'))
        .key('H', MetaTileEntities.HULL[GTValues.HV].getStackForm())
        .output(item('enderutilities:storage_0'))
        .replace()
        .register()
// memory chest
crafting.shapedBuilder()
        .row(' C ')
        .row(' H ')
        .row('   ')
        .key('C', ore('circuitEv'))
        .key('H', item('enderutilities:storage_0'))
        .output(item('enderutilities:storage_0', 1))
        .replace()
        .register()
// handy chest (small)
crafting.shapedBuilder()
        .row(' C ')
        .row(' H ')
        .row(' C ')
        .key('C', ore('circuitHv'))
        .key('H', MetaTileEntities.HULL[GTValues.HV].getStackForm())
        .output(item('enderutilities:storage_0', 3))
        .replace()
        .register()
// handy chest (normal)
crafting.shapedBuilder()
        .row(' C ')
        .row(' H ')
        .row(' C ')
        .key('C', ore('circuitEv'))
        .key('H', item('enderutilities:storage_0', 3))
        .output(item('enderutilities:storage_0', 4))
        .replace()
        .register()
// memory card (items) 8 B
crafting.shapedBuilder()
        .row('   ')
        .row('PCP')
        .row('PHP')
        .key('P', item('enderio:item_alloy_ingot', 5))
        .key('C', ore('circuitEv'))
        .key('H', MetaTileEntities.HULL[GTValues.EV].getStackForm())
        .output(item('enderutilities:enderpart', 52))
        .replace()
        .register()
// handy bag (large)
crafting.shapedBuilder()
        .row('PHP')
        .row('HCH')
        .row('PHP')
        .key('P', item('enderio:item_alloy_ingot', 5))
        .key('H', item('enderutilities:handybag'))
        .key('C', ore('circuitEv'))
        .output(item('enderutilities:handybag', 1))
        .replace()
        .register()
// pyrotheum dust
crafting.removeByOutput(item('thermalfoundation:material', 1024))
// cryotheum dust
crafting.removeByOutput(item('thermalfoundation:material', 1025))