import classes.TJMetaTileEntities
import gregtech.api.unification.OreDictUnifier
import gregtech.api.unification.material.Materials
import gregtech.api.unification.ore.OrePrefix
import gregtech.common.blocks.BlockMetalCasing
import gregtech.common.blocks.MetaBlocks
import gregtech.common.metatileentities.MetaTileEntities

// steam motor
crafting.shapedBuilder()
        .row('SPR')
        .row('PRP')
        .row('IPS')
        .key('S', OreDictUnifier.get(OrePrefix.stick, Materials.Wood))
        .key('P', OreDictUnifier.get(OrePrefix.plate, Materials.Bronze))
        .key('R', OreDictUnifier.get(OrePrefix.stick, Materials.Iron))
        .key('I', OreDictUnifier.get(OrePrefix.ingot, Materials.Iron))
        .output(item('technological_journey:steammotor'))
        .register()
// steam piston
crafting.shapedBuilder()
        .row('GSS')
        .row('GMB')
        .row('PPP')
        .key('G', OreDictUnifier.get(OrePrefix.gearSmall, Materials.Iron))
        .key('S', OreDictUnifier.get(OrePrefix.stick, Materials.Wood))
        .key('M', item('technological_journey:steammotor'))
        .key('B', OreDictUnifier.get(OrePrefix.plate, Materials.Bronze))
        .key('P', OreDictUnifier.get(OrePrefix.plate, Materials.Iron))
        .output(item('technological_journey:steampiston'))
        .register()
// hot iron ingot
furnace.add(ore('ingotIron'), item('technological_journey:hotiron'))
// industrial primitive blast furnace
crafting.shapedBuilder()
        .row('BFB')
        .row('FEF')
        .row('BFB')
        .key('B', MetaBlocks.METAL_CASING.getItemVariant(BlockMetalCasing.MetalCasingType.PRIMITIVE_BRICKS))
        .key('F', item('minecraft:furnace'))
        .key('E', MetaTileEntities.PRIMITIVE_BLAST_FURNACE.getStackForm())
        .output(TJMetaTileEntities.INDUSTRIAL_PRIMITIVE_BLAST_FURNACE.getStackForm())
        .register()
// portal to the void
crafting.shapedBuilder()
        .row('OIO')
        .row('IPI')
        .row('OIO')
        .key('O', ore('obsidian'))
        .key('I', item('minecraft:diamond'))
        .key('P', item('minecraft:iron_pickaxe'))
        .output(item('simplevoidworld:portal'))
        .replace()
        .register()
// ender fluid conduit
crafting.shapedBuilder()
        .row('BBB')
        .row('PCP')
        .row('BBB')
        .key('B', item('enderio:item_material', 4))
        .key('P', item('enderio:item_alloy_nugget', 5))
        .key('C', item('enderio:item_liquid_conduit', 1))
        .output(item('enderio:item_liquid_conduit', 2) * 8)
        .replace()
        .register()
crafting.shapedBuilder()
        .row('BBB')
        .row('PCP')
        .row('BBB')
        .key('B', item('enderio:item_material', 4))
        .key('P', item('enderio:item_alloy_nugget', 5))
        .key('C', ore('fusedQuartz'))
        .output(item('enderio:item_liquid_conduit', 2) * 8)
        .register()
// grindstone
mods.astralsorcery.starlight_altar.removeByOutput(item('astralsorcery:blockmachine', 1))
crafting.shapedBuilder()
        .row(' I ')
        .row('POS')
        .row('PPM')
        .key('I', OreDictUnifier.get(OrePrefix.dust, Materials.Iron))
        .key('P', OreDictUnifier.get(OrePrefix.plank, Materials.Wood))
        .key('O', item('minecraft:stone'))
        .key('S', OreDictUnifier.get(OrePrefix.stick, Materials.Wood))
        .key('M', item('technological_journey:steammotor'))
        .output(item('astralsorcery:blockmachine', 1))
        .register()
// tree beacon
mods.astralsorcery.starlight_altar.removeByOutput(item('astralsorcery:blocktreebeacon'))
crafting.shapedBuilder()
        .row('CSC')
        .row('PCP')
        .row('PPP')
        .key('C', ore('circuitLv'))
        .key('S', ore('treeSapling'))
        .key('P', OreDictUnifier.get(OrePrefix.plate, Materials.Steel))
        .output(item('astralsorcery:blocktreebeacon'))
        .register()
// enderio alloy smelter
mods.enderio.alloy_smelter.removeAll()
// enderio sag mill
mods.enderio.sag_mill.removeAll()
mods.enderio.sag_mill_grinding.removeAll()
// enderio combustion generator
mods.enderio.fluid_fuel.removeAll()
